name: First Workflow

on:
  - push

jobs: 
    first_job: ikes-k8s
        runs-on: ubuntu-latest
        steps:
            - name: First Message
              run: echo "Welcome to CI/CD via GitHu Actions"

            - name: List All Files including Hidden Ones
              run: ls -1a

            - name: Show Current Directory
              run: pwd