name: Second Workflow

on:
  - push

jobs: 
    first_job: 
        name: darks_k8s 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: List and Read files
              run: |
                echo "My first GitHu Actions Job"
                ls -1
                cat dockerfile